### ISSUE TITLE
Kernel patch for >64GB RAM systems

### ISSUE THREAD

**Issue by markusbkk** [eltanin-os/glacies#2]
I don't have the machine to test this on yet but when you next upgrade the Arbor packages, could you please ensure the included kernel ships with this patch?

https://github.com/torvalds/linux/commit/08fffa74d9772d9538338be3f304006c94dde6f0

Without the patch, there's a fair chance the screen will just flicker uncontrollably on really beefy systems (see [here](https://knowledgebase.frame.work/what-ram-memory-is-supported-in-framework-laptop-13-ryzen-7040-series-B1M60foth)).

PS: Any reason why you're still shipping with 4.19? Is it because it was the LTS kernel release when you started this project? It's quite old now and will reach EOL on New Year's Eve 2024.

**Comment by eadwardus** [comment]
> Any reason why you're still shipping with 4.19?

When I chose the version were planning on shipping OSS (the audio system) along with the kernel and 4.X would make it easier to do so.

> will reach EOL on New Year's Eve 2024.

Yeah, I'm planning on updating to another LTS version, likely 5.15.

> patch

If the next version get to be 5.X, I'm not sure if it's applicable, the files are not the same to patch (and with Linux you can, usually, assume the interface isn't either). I would expect that any LTS version would backport security/functionality patches but I'll give it a look.

**Comment by markusbkk** [comment]
Thanks for looking into it.

Been trying to build everything myself this afternoon but I keep running into issues.
If I try compiling Redo right after Tertium, there's undefined references to things like `c_sys_clockgettime`.

I think I saw those symbols inside Simia but Simia itself won't compile with the current Tertium.

**Comment by eadwardus** [comment]
It was on the docs before but were lost when I changed the site engine, still didn't repopulate the new one (docs.eltaninos.org). The declarative nature of make won't let it generate the sys files (os + platform dependent) and use them as deps (for they are "unknown" targets until generated).
```
cd tertium
make src/sys
make
```
To compile tertium correctly.

**Comment by eadwardus** [comment]
The kernel has been updated to 6.6.X which should include the proposed patch, so closing the issue.
